[New Game]: Black Jack
kunjgit/GameZone pull request #175
Opened 2023-05-21 13:22 UTC by singh-anushka

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes [#82](https://github.com/kunjgit/GameZone/issues/82)

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

<img width="1440" alt="Black_Jack" src="https://github.com/kunjgit/GameZone/assets/93376863/3c7490ca-b470-40c0-8a42-5136e084a713">

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-05-21 13:23 UTC, kunjgit commented
Thank you @singh-anushka ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2023-05-22 16:21 UTC, kunjgit commented
Hey @singh-anushka 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

2023-05-23 19:22 UTC, singh-anushka commented
@kunjgit Kindly look into the PR as I resolved the merge conflict too.

2023-05-25 08:43 UTC, kunjgit requested changes
Just make sure you add your game entry with game number * in main README file !! 👀 
and rename your own readme !! All other things are fine 🔥

2023-05-25 08:43 UTC, kunjgit commented on Games/Black_Jack/ReadMe.md
Hey !
Rename file to README.md
 so it can be detected 👀

2023-05-25 08:52 UTC, singh-anushka commented on Games/Black_Jack/ReadMe.md
Done, Please check and merge these PRs too!
[Atari Breakout game](https://github.com/kunjgit/GameZone/pull/302)
[Guess Colour by RGB game](https://github.com/kunjgit/GameZone/pull/312)
[Resolving responsiveness bug of the main website](https://github.com/kunjgit/GameZone/pull/339)
[Chrome Dinosaur game](https://github.com/kunjgit/GameZone/pull/345)

2023-05-25 08:58 UTC, singh-anushka commented
Changes done! Please merge this PR @kunjgit
And please check and merge these PRs too!

[Atari Breakout Game](https://github.com/kunjgit/GameZone/pull/302)
[Guess Colour by RGB](https://github.com/kunjgit/GameZone/pull/312)
[Resolve responsiveness bug of the main website](https://github.com/kunjgit/GameZone/pull/339)
[Chrome Dinosaur](https://github.com/kunjgit/GameZone/pull/345)

Also please add the GSSOC23 label along with the difficulty level 3 card to it too while merging. Thank you!

2023-05-25 11:45 UTC, kunjgit approved these changes

2023-05-25 11:45 UTC, merged

2023-05-25 11:46 UTC, kunjgit commented
Thank you  @singh-anushka , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀