Add Save The Mouse Game
kunjgit/GameZone pull request #2009
Opened 2023-06-25 15:09 UTC by Sriparno08

## PR Description 📜

Fixes #2000

This PR is part of GSSoC'23.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Save_The_Mouse](https://github.com/kunjgit/GameZone/assets/89148144/b21f63e3-3e2f-4c13-aec4-603a2b0832b5)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-06-25 15:09 UTC, kunjgit commented
Thank you @Sriparno08 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2023-06-27 05:34 UTC, kunjgit approved these changes

2023-06-27 06:19 UTC, gurjeetsinghvirdee approved these changes

2023-06-27 10:18 UTC, gurjeetsinghvirdee requested changes
Resolve the conflicts

2023-06-27 11:07 UTC, gurjeetsinghvirdee reviewed
**Code copied from Codepen: https://codepen.io/chaofix/pen/VrWZga**

2023-06-27 11:07 UTC, closed without merging