Stick The Sticker Game
kunjgit/GameZone pull request #2126
Opened 2023-06-28 08:28 UTC by Tisha6661

## PR Description 📜
In this game there are several stickers given in various pieces. The pieces can be shuffled to form a meaningful sticker.

Fixes # <your_issue_number> 
#2119 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![image](https://github.com/kunjgit/GameZone/assets/98682478/88720816-1da5-42ea-a82e-e4aae35c6c9b)
![image](https://github.com/kunjgit/GameZone/assets/98682478/41bd0b34-523c-4be9-ad1f-c76fa5b3e3ea)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-06-28 08:29 UTC, kunjgit requested changes
Hello @Tisha6661,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2023-06-28 08:32 UTC, Tisha6661 commented
@kunjgit I have made the changes you asked-
![image](https://github.com/kunjgit/GameZone/assets/98682478/ce7ebf85-818c-443c-ba36-d22d8dcab53d)
![image](https://github.com/kunjgit/GameZone/assets/98682478/2bc39376-769a-4d13-b080-cc0a4aa1b04c)

2023-07-05 16:11 UTC, kunjgit approved these changes

2023-07-05 16:12 UTC, merged

2023-07-05 16:12 UTC, kunjgit requested changes
Hello @Tisha6661,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀