Image Flash Quiz Game
kunjgit/GameZone pull request #2238
Opened 2023-07-02 12:55 UTC by shubhisingh184

forked updation

## PR Description 📜
Added Image Flash Quiz Game

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2128 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Image_Flash_Game](https://github.com/kunjgit/GameZone/assets/67328331/677bad54-96ec-41a7-8a48-07e0d6fa680c)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-07-02 12:55 UTC, kunjgit commented
Thank you @shubhisingh184 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2023-07-02 12:56 UTC, kunjgit requested changes
Hello @shubhisingh184,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2023-07-02 13:00 UTC, kunjgit approved these changes

2023-07-02 13:25 UTC, shubhisingh184 commented on Games/Image_Flash_Game/index.html
> +    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
Thank you for pointing out. I'll  will conduct thorough integrity checks on any scripts loaded from the content delivery network to verify their authenticity and integrity. From my point of view, it's safe. Let me know if you want any changes.

2023-07-12 09:56 UTC, closed without merging

2023-07-12 09:56 UTC, kunjgit commented
Hey @shubhisingh184,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

2023-07-12 09:56 UTC, kunjgit commented
Thank you  @shubhisingh184 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀