New game Claw Crane added
kunjgit/GameZone pull request #2750
Opened 2023-08-04 07:26 UTC by vbhosale11

## PR Description 📜

A new game Claw Crane has been added to the gamezone . Use the joystick to position the claw, and press slider  to grab a prize . Collect the prize if successful.
Fixes #2707 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![clawCrane](https://github.com/kunjgit/GameZone/assets/106435329/b0e1b37a-edf3-4ffa-8777-3f9a3c282078)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-08-04 07:26 UTC, kunjgit commented
Thank you @vbhosale11 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2023-08-06 16:41 UTC, gurjeetsinghvirdee approved these changes

2023-08-06 16:42 UTC, gurjeetsinghvirdee requested changes
Hey @vbhosale11 
Please add your game in the Readme file of the project & add one screenshot in assets/image directory

2023-08-08 19:38 UTC, gurjeetsinghvirdee approved these changes

2023-08-08 19:39 UTC, merged

2023-08-08 19:39 UTC, kunjgit commented
Thank you  @vbhosale11 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀