Tic Tac Toe Game
kunjgit/GameZone pull request #3182
Opened 2024-05-12 13:00 UTC by RazaAli313

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # < 3173>
Issue Number #3173

<hr>
 
## Mark the task you have completed ✅
I have built # Tic Tac Toe
# Description 📃
This is a classic Tic Tac Toe game implemented with additional functionalities such as success music on winning, music on game drawn, and sound on each click of turn. The game features a user-friendly interface and supports both single-player and two-player modes.

## Functionalities 🎮
- [x] Play against another player
- [x] Success music on winning
- [x] Music on game drawn
- [x] Sound on each click of turn
- [ ] Recognizes winning combinations horizontally, vertically, and diagonally
- [x] Attractive UI

## How to Play? 🕹️
1. Launch the game.
2. Click on the desired cell to place your symbol (X or O).
3. Alternate turns with your opponent.
4. The first player to achieve three of their symbols in a row wins.
5. If all cells are filled and no player has three symbols in a row, the game is drawn.

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-05-12 13:00 UTC, kunjgit commented
Thank you @RazaAli313 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-05-12 13:03 UTC, RazaAli313 commented
@kunjgit Sir kindly review My PR

2024-06-13 16:39 UTC, ishita-43 requested changes

2024-06-13 16:39 UTC, ishita-43 commented on README.md
> +Tic Tac Toe(https://github.com/RazaAli313/GameZone/tree/main/Games/Tic_Tac_Toe_Game)|                                                                                                                 |
follow the format while entering your game

2024-07-27 02:40 UTC, ishita-43 commented on README.md
> +Tic Tac Toe(https://github.com/RazaAli313/GameZone/tree/main/Games/Tic_Tac_Toe_Game)|                                                                                                                 |
Instead of your repository name update this with kunjgit to makke it workable on the website

2024-07-27 02:43 UTC, ishita-43 commented on README.md
> +Tic Tac Toe(https://github.com/RazaAli313/GameZone/tree/main/Games/Tic_Tac_Toe_Game)|                                                                                                                 |
Manually resolved will now be merged

2024-07-27 02:44 UTC, ishita-43 approved these changes
Ready to merge

2024-07-27 10:30 UTC, merged

2024-07-27 10:30 UTC, kunjgit commented
Thank you  @RazaAli313 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀