Added Flames Game
kunjgit/GameZone pull request #3855
Opened 2024-05-28 16:12 UTC by Saipradyumnagoud

## PR Description 📜

Added Flames game where user can give there name and crush name to find the relation

Fixes #3822 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-05-28 16:12 UTC, kunjgit commented
Thank you @Saipradyumnagoud ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-05-28 16:13 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-05-28 16:16 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-05-28 16:18 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-05-28 16:18 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-05-28 16:20 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-05-28 16:20 UTC, Saipradyumnagoud commented
What should i modify in readme

2024-05-28 16:21 UTC, Saipradyumnagoud commented
I have added assets/images directory 
I have added Readme.md file also
could you please tell me what else should I do

2024-05-29 01:49 UTC, kunjgit requested changes
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-05-29 02:06 UTC, Saipradyumnagoud reviewed
I Have modified main ReadMe File

2024-05-29 02:06 UTC, Saipradyumnagoud commented on README.md
> -|[Flames-Game](https://github.com/Saipradyumnagoud/GameZone/tree/main/Games/Flames-game) |
I have modified  Main ReadMe file

2024-05-29 02:07 UTC, Saipradyumnagoud commented
> Hello @Saipradyumnagoud, You need to make the following changes:
> 
> * Please modify the main README.md file.
> 
> Hoping that you will make those changes soon 🚀

I Have modified Main ReadMe.md file please check it

2024-05-29 15:12 UTC, kunjgit commented
@Saipradyumnagoud you are having submodule in your code make sure you are following proper guidelines !
make PR again after that!

2024-05-29 15:12 UTC, closed without merging