Completed making Emoji Charades game
kunjgit/GameZone pull request #398
Opened 2023-05-25 08:33 UTC by akhilender-bongirwar

## PR Description 📜
Made a challenging emoji charades game which requires players high relatable knowledge.
Fixes #388 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![image](https://github.com/kunjgit/GameZone/assets/112749383/c609cc70-c55c-4b48-aeba-3b47e33b61db)

--- 
<br>
## Add your video(Optional) 📸

https://github.com/kunjgit/GameZone/assets/112749383/6ac333a6-0b98-4b84-ae72-c4ae3c77c349

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-05-27 05:29 UTC, kunjgit requested changes
rename your readme to README and also mark your entry in main README file !!

2023-05-30 09:14 UTC, akhilender-bongirwar commented
> rename your readme to README and also mark your entry in main README file !!

Made all the changes as required. Please check it.

2023-06-02 10:35 UTC, kunjgit approved these changes

2023-06-02 10:35 UTC, merged

2023-06-02 10:36 UTC, kunjgit commented
Thank you  @akhilender-bongirwar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀