Arrow strike
kunjgit/GameZone pull request #4054
Opened 2024-06-01 10:41 UTC by Nikuunj

## Issue #4052 

# Basic description
Arcane Archer is a captivating journey where players master the art of archery amidst mystical landscapes. With intuitive controls and magical abilities, players embark on quests, face mythical creatures, and compete in thrilling tournaments. Become a legend of the bow in Arcane Archer.
<hr>

## Checkpoint 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Screenshot 2024-06-01 160359](https://github.com/kunjgit/GameZone/assets/134833235/86ab7dee-fa51-421c-a563-63a98a0b791a)

--- 
<br>

2024-06-01 10:41 UTC, kunjgit commented
Thank you @Nikuunj ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-01 10:41 UTC, kunjgit requested changes
Hello @Nikuunj,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-01 10:42 UTC, Nikuunj commented
@kunjgit ohkk

2024-06-01 10:48 UTC, kunjgit requested changes
Hello @Nikuunj,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-01 10:50 UTC, Nikuunj commented
@kunjgit

2024-06-02 18:12 UTC, Nikuunj commented
@kunjgit

2024-06-03 13:52 UTC, kunjgit requested changes
@Nikuunj make sure you are adding your game entry in main readme and also adding your game image in assets!

2024-06-03 17:54 UTC, Nikuunj commented
@kunjgit

2024-06-24 16:41 UTC, ishita-43 commented
Please resolve merge conflicts in index old file

2025-03-21 12:39 UTC, closed without merging