Fidget spinner #4119
kunjgit/GameZone pull request #4142
Opened 2024-06-03 02:07 UTC by nisargaa20

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

Fidget Spinner is an interactive online simulation of a physical fidget spinner. This digital version allows users to experience the satisfying and stress-relieving sensation of spinning a fidget spinner directly from their browser.

Interactive Spinning: Users can spin the fidget spinner by dragging the mouse across the screen.
Speed Display: The current speed of the spinner is displayed, giving users real-time feedback.
Custom Speed Setting: Users can set a custom speed for the fidget spinner, allowing for a personalized experience.
Automatic Spin: For those who prefer not to drag their mouse, a button is available to automatically spin the fidget spinner.
How to Play? 🕹️
Drag to Spin: Click and drag the mouse across the spinner to make it spin. The faster you drag, the faster the spinner will rotate.
View Speed: Watch the speedometer to see how fast the spinner is going.
Set Custom Speed: Use the input box to set a custom speed for the spinner.
Automatic Spin: Click the "Spin" button to make the spinner spin without dragging.

Fixed #4119

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Uploading Fidget.png…]()

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-03 02:07 UTC, kunjgit commented
Thank you @nisargaa20 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-04 06:48 UTC, nisargaa20 commented
@kunjgit Kindly review it sooner as it getting conflicts

2024-06-05 01:53 UTC, nisargaa20 commented
@kunjgit kindly add labels

2024-06-06 13:24 UTC, nisargaa20 commented
/assign

2024-06-07 12:02 UTC, nisargaa20 commented
@kunjgit kindly add labels and review it . It has been 4 days I need to raise new issue

2024-06-08 12:07 UTC, nisargaa20 commented
@ishita-43 Kindly check it out the PR and add labels

2024-06-11 03:40 UTC, nisargaa20 commented
@kunjgit Its been a week kindly check it out ( conflicting is occuring)

2024-06-11 12:35 UTC, ishita-43 requested changes
Make the desired changes!!

2024-06-11 12:35 UTC, ishita-43 commented on README.md
> +| [Hit_the_hamster] (https://github.com/kunjgit/GameZone/tree/main/Games/Hit_the_hamster)                |
delete this duplicate entry from here

2024-06-11 12:35 UTC, ishita-43 commented on assets/js/gamesData.json
> +  ,"417":{
remove all these entry and place your below each entry with no 417
or arrange the entry in the order 
417
409
418
410
and so on at the bottom of file

2024-06-11 12:48 UTC, nisargaa20 commented
@ishita-43 done check it out

2024-06-11 13:22 UTC, ishita-43 requested changes

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"409":{
change as 418

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +"418":{
409

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"417":{
410

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +"418":{"gameTitle": "Pen_Pointer_Fight",
411

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"410":{
419

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> + "409":{
420

2024-06-11 13:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +"410":{
421

2024-06-11 13:34 UTC, nisargaa20 commented
@ishita-43 I got confused while doing check it out if its correct

2024-06-11 13:46 UTC, ishita-43 commented
> @ishita-43 I got confused while doing check it out if its correct

ok you need to make changes in such a way that the number increase alternatingly 
eg if you ha 407 416 these two entries in the end then make increament alternatinly eg first increase first number than second number so for above examolle series would be 
407 416 than
408 417 409 418 410 and keep this increasing till all entries get nubered did you get this!!

2024-06-11 13:50 UTC, nisargaa20 commented
@ishita-43 Thank you got it now . I have made the changes check it out

2024-06-20 11:38 UTC, ishita-43 commented
Merge conflicts are arising please do one think sync your json and readme file and then add again add your game there and then upload them here!!

2024-06-20 14:15 UTC, nisargaa20 commented
@ishita-43 kindly merge it soon or else again there will be conflict if u merge others PR

2024-06-21 16:50 UTC, ishita-43 approved these changes
Seems good!!

2024-06-21 17:07 UTC, nisargaa20 commented
@ishita-43 Kindly merge it

2024-06-22 16:48 UTC, merged

2024-06-22 16:48 UTC, kunjgit commented
Thank you  @nisargaa20 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀