IMPROVE THE BACKGROUND OF SPELLING BEE GAME
kunjgit/GameZone pull request #4166
Opened 2024-06-03 14:13 UTC by TusharChamlikar

## PR Description 📜

Fixes #4163
the background of spelling bee game was simple, i made it attractive by changing background.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
![Screenshot 2024-06-03 194225](https://github.com/kunjgit/GameZone/assets/153795768/08c752de-1b40-40de-b015-76b77d14292d)

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-04 08:55 UTC, TusharChamlikar commented
@kunjgit please merge my request sir

2024-06-04 14:24 UTC, TusharChamlikar commented
@kunjgit

2024-06-05 14:27 UTC, TusharChamlikar commented
@kunjgit sir plz merge my request

2024-06-06 12:26 UTC, TusharChamlikar commented
@kunjgit

2024-06-08 07:14 UTC, ishita-43 requested changes
Make clear PR only making changes in desired game and not tempering with others!!
Hoping you will make changes soon!!

2024-06-08 07:14 UTC, ishita-43 commented on Games/Chrome_Dinosaur_Game/dino.jpg
Remove file if not needed!!

2024-06-08 07:14 UTC, ishita-43 commented on Games/Chrome_Dinosaur_Game/th.jpeg
Remove if not impacting the results!!

2024-06-08 09:08 UTC, closed without merging

2024-06-08 09:08 UTC, kunjgit commented
Thank you  @TusharChamlikar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀