Added a new game
kunjgit/GameZone pull request #4196
Opened 2024-06-03 19:38 UTC by codewithishu

fixes #4194 
 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸
![Screenshot 2024-06-04 004406](https://github.com/kunjgit/GameZone/assets/146975269/542321f6-b161-4a94-9017-f21bf18ee726)

2024-06-03 19:38 UTC, kunjgit commented
Thank you @codewithishu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-06 20:45 UTC, codewithishu commented
Can you merge it

2024-06-09 18:16 UTC, ishita-43 requested changes
do same for all the images used in assests folder

2024-06-09 18:16 UTC, ishita-43 commented on assets/images/og-image (1).png
Rename the images in assets folder according to the contribution guidelines

2024-06-09 19:14 UTC, codewithishu commented on assets/images/og-image (1).png
Okay

2024-06-09 19:44 UTC, kunjgit commented
Thank you  @codewithishu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

2024-06-09 19:45 UTC, codewithishu commented
> do same for all the images used in assests folder

I have done it

2024-06-09 19:46 UTC, codewithishu commented on assets/images/og-image (1).png
i have renamed it

2024-06-09 19:46 UTC, codewithishu commented
@kunjgit please merge it

2024-06-09 19:50 UTC, ishita-43 requested changes

2024-06-09 19:50 UTC, ishita-43 commented on assets/images/og-image.png
remove this if not needed

2024-06-09 19:51 UTC, ishita-43 requested changes

2024-06-09 19:51 UTC, ishita-43 commented on Games/Wordling/_config.yml
empty file remove this!!

2024-06-09 19:51 UTC, ishita-43 commented on Games/Wordling/dictionary.js
also empty remove!!

2024-06-09 19:54 UTC, ishita-43 commented on Games/Wordling/index.js
empty !! remove this if not needed

2024-06-09 19:54 UTC, ishita-43 commented on Games/Wordling/package.json
Empty remove this if not needed!!

2024-06-09 19:54 UTC, ishita-43 commented on Games/Wordling/style.css
remove this if not needed

2024-06-09 20:28 UTC, codewithishu commented on assets/images/og-image.png
done

2024-06-11 17:11 UTC, ishita-43 commented
Please try to resolve merge conflicts

2024-06-14 17:31 UTC, codewithishu commented
@kunjgit please merge it

2024-06-16 04:56 UTC, ishita-43 approved these changes
good to go!

2024-06-16 14:10 UTC, merged

2024-06-16 14:10 UTC, kunjgit commented
Thank you  @codewithishu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀