Solved issue #4187- Tower Defence Game
kunjgit/GameZone pull request #4197
Opened 2024-06-03 19:39 UTC by Aditi22Bansal

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
In this game, players place defensive towers along a path to stop waves of enemies from reaching the end. Each tower has different abilities and ranges, and players can upgrade towers to improve their effectiveness.

Fixes # <your_issue_number>
Fixes #4187 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Screenshot 2024-06-04 004952](https://github.com/kunjgit/GameZone/assets/142652964/9044c682-ce1e-4b3d-8ffe-36f80b600510)
![Screenshot 2024-06-04 005003](https://github.com/kunjgit/GameZone/assets/142652964/3c888207-125d-4a38-a6ff-a9ff607066bd)
![Screenshot 2024-06-04 005020](https://github.com/kunjgit/GameZone/assets/142652964/acd179b3-015d-43ca-9c60-c7b6a6dd927a)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-03 19:39 UTC, kunjgit commented
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-03 19:39 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review and merge

2024-06-03 19:40 UTC, kunjgit requested changes
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-03 19:43 UTC, Aditi22Bansal commented
@kunjgit 
Kindly check I have added

2024-06-03 19:46 UTC, Aditi22Bansal commented
@kunjgit 
Done

2024-06-04 04:42 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review and merge

2024-06-04 08:08 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review and merge

2024-06-04 15:33 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review and merge
Thankyou

2024-06-05 16:25 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review and merge

2024-06-06 18:34 UTC, Aditi22Bansal commented
@ishita-43 
Kindly review this PR

2024-06-08 08:57 UTC, Aditi22Bansal commented
@ishita-43 
Kindly review this PR so that I can work on the other issue you have assigned me

2024-06-08 09:01 UTC, ishita-43 requested changes
Please make the following changes:- ⚠ 
Follow contribution guidelines while naming the images in assets folder
Do not place images outside of your game folder instead place it in your game folder.

i hope you will make changes soon!!

2024-06-08 09:03 UTC, Aditi22Bansal commented
ok

2024-06-08 09:08 UTC, Aditi22Bansal commented
@ishita-43 
I have done the required changes
Kindly review 
If any changes are required kindly tell

2024-06-08 09:17 UTC, ishita-43 requested changes
Also change the path of images if used anywhere in the program

2024-06-08 09:17 UTC, ishita-43 commented on Screenshot 2024-06-04 005020.png
remove this one..

2024-06-08 09:17 UTC, ishita-43 commented on Tower game.png
remove this one..

2024-06-08 09:17 UTC, ishita-43 commented on assets/images/Tower_Game.png
name as "Tower_Defence_Game.png"

2024-06-08 13:22 UTC, closed without merging