Fixing theme toggle
kunjgit/GameZone pull request #4204
Opened 2024-06-04 05:58 UTC by Jasleen1210

The issue with the inversion of game images during light theme has been fixed. Only the game images are unaffected by the toggle and the font footer changes remain same as original. Also edited gamesData.json such that the games are in order and closed a bracket that was accidentally left open and causing error in the site.
## PR Description 📜

Fixes #4148

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
<img width="959" alt="game" src="https://github.com/kunjgit/GameZone/assets/144164397/4bea7291-7c9a-4a8f-98cf-827bce458789">
<img width="959" alt="zone" src="https://github.com/kunjgit/GameZone/assets/144164397/0cbeef37-8c38-482f-b292-758d114f9c44">

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-04 05:58 UTC, kunjgit commented
Thank you @Jasleen1210 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-25 04:41 UTC, ishita-43 commented
Please resolve merge conflicts

2024-06-25 05:05 UTC, Jasleen1210 commented
Done! @ishita-43

2024-07-04 07:12 UTC, ishita-43 requested changes

2024-07-04 07:12 UTC, ishita-43 commented on assets/js/gamesData.json
> +=======
REMOVE THIS LINE

2024-07-04 07:12 UTC, ishita-43 commented on assets/js/gamesData.json
> +=======
REMOVE THIS

2024-07-17 16:34 UTC, ishita-43 approved these changes
Ready to merge

2024-07-17 17:34 UTC, merged

2024-07-17 17:35 UTC, kunjgit commented
Thank you  @Jasleen1210 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀