CREATED THE GAME ELEPHANT ANT MAN
kunjgit/GameZone pull request #4219
Opened 2024-06-04 16:45 UTC by tanishkaa08

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4015 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-04 16:45 UTC, kunjgit commented
Thank you @tanishkaa08 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-05 07:22 UTC, tanishkaa08 commented
Please review it.

2024-06-25 04:50 UTC, ishita-43 requested changes
Hoping you will make desired changes soon!!!

2024-06-25 04:50 UTC, ishita-43 commented on assets/images/screenshot.png
rename your image name as per naming conventions in contribution guidelines.

2024-06-25 04:50 UTC, ishita-43 commented on README.md
> -<br>
add this line again

2024-06-25 04:50 UTC, ishita-43 commented on README.md
> +|[Elephant_ant_man](https://github.com/tanishkaa08/GameZone/tree/main/Games/Elephant_ant_man)    |
follow other entries format while providing the link it should start with kunjgit instead of tanishkaa

2024-07-27 06:51 UTC, ishita-43 approved these changes
Conflicts resolved

2024-07-27 10:30 UTC, merged

2024-07-27 10:30 UTC, kunjgit commented
Thank you  @tanishkaa08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀