Added bounce ball game
kunjgit/GameZone pull request #4220
Opened 2024-06-04 17:01 UTC by YadlaMani

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-04 17:01 UTC, kunjgit commented
Thank you @YadlaMani ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-04 17:16 UTC, YadlaMani commented
@kunjgit fixed the readme with the changes you requested

2024-06-04 17:20 UTC, YadlaMani commented
@kunjgit  done the requested changes

2024-06-04 17:21 UTC, kunjgit requested changes
Hello @YadlaMani,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-04 17:25 UTC, YadlaMani commented
@kunjgit yeah done the changes

2024-06-25 04:52 UTC, ishita-43 requested changes

2024-06-25 04:52 UTC, ishita-43 commented on assets/images/Screenshot 2024-06-04 224119.png
rename the image per naming convention mentioned in the contribution guidelines

2024-06-25 04:52 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)
remove the duplicate entry

2024-07-27 06:56 UTC, ishita-43 approved these changes
Ready to merge

2024-08-08 11:05 UTC, merged

2024-08-08 11:05 UTC, kunjgit commented
Thank you  @YadlaMani , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀