Add new Game Language Learner Adventure
kunjgit/GameZone pull request #4261
Opened 2024-06-05 17:55 UTC by bhaveshnegi

## PR Description 📜

Objective:
The goal of the game is to help players learn new vocabulary by matching words with their correct translations. Players answer multiple-choice questions and receive feedback on their answers. A scoring system tracks their progress.
Fixes #4257 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [x ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-05 17:55 UTC, kunjgit commented
Thank you @bhaveshnegi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-09 13:13 UTC, ishita-43 requested changes
Enter your game in readme file properly

2024-06-09 13:13 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)         |
Remove this duplicate and make only entry of your game 
remove rapid click frenzy one

2024-06-10 06:58 UTC, bhaveshnegi commented
@ishita-43 i have resolve the conflicts

2024-06-12 08:45 UTC, closed without merging

2024-06-12 08:45 UTC, kunjgit commented
Thank you  @bhaveshnegi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀