fixed #4259
kunjgit/GameZone pull request #4277
Opened 2024-06-06 07:43 UTC by dnyandeepchute

## PR Description 📜
text was not visible in light mode
Fixes #4259

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

before:
![Screenshot 2024-06-06 124131](https://github.com/kunjgit/GameZone/assets/158272735/08d9f2fc-723a-4089-965b-e7ea7177e7b7)
![Screenshot 2024-06-06 124140](https://github.com/kunjgit/GameZone/assets/158272735/61cb021b-e525-41d9-8ffa-0be2efdcfe2a)

after:
![Screenshot 2024-06-06 124103](https://github.com/kunjgit/GameZone/assets/158272735/a1148655-7882-4827-b547-86e6727f9f71)
![Screenshot 2024-06-06 124117](https://github.com/kunjgit/GameZone/assets/158272735/f962accd-74ae-4368-9488-a0f5df2b40bf)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-06 07:43 UTC, kunjgit commented
Thank you @dnyandeepchute ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-06 07:44 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-06 09:34 UTC, dnyandeepchute commented
@kunjgit it was a bug, please review it.

2024-06-07 05:23 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-07 05:29 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-07 05:32 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-07 05:39 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-07 05:41 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-07 05:46 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-07 11:16 UTC, dnyandeepchute commented
@kunjgit please merge this, thank you.

2024-06-09 13:37 UTC, ishita-43 requested changes
You dont need extra files for bug correction remove those files !!
Hoping you will make changes soon!!

2024-06-09 13:37 UTC, ishita-43 commented on Games/demo/style.css
delete this file if not needed!!

2024-06-09 13:37 UTC, ishita-43 commented on Games/demo/index.html
delete this file if not needed!!

2024-06-09 13:37 UTC, ishita-43 commented on Games/demo/README.md
This file is not nedded !! Remove this one..

2024-06-09 13:47 UTC, kunjgit requested changes
Hello @dnyandeepchute,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-09 13:48 UTC, dnyandeepchute commented
done please check.

2024-06-09 13:48 UTC, dnyandeepchute commented on Games/demo/README.md
done please check.

2024-06-09 13:49 UTC, dnyandeepchute commented on Games/demo/index.html
done please check.

2024-06-09 13:49 UTC, dnyandeepchute commented on Games/demo/style.css
done please check.

2024-06-09 14:05 UTC, ishita-43 approved these changes
Good to go!!

2024-06-09 14:15 UTC, dnyandeepchute commented
@ishita-43 it was for level3, is it??

2024-06-09 14:48 UTC, ishita-43 commented
> @ishita-43 it was for level3, is it??

YOU DID bug removal right!!
If its the case we place bugs removal in level1

2024-06-10 12:52 UTC, merged

2024-06-10 12:53 UTC, kunjgit commented
Thank you  @dnyandeepchute , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀