Added Grab The carrot
kunjgit/GameZone pull request #4284
Opened 2024-06-06 10:06 UTC by Aksshay88

## PR Description 📜
I have included the Grab the carrot game where the user could play the game
Fixes #4201

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-06 10:06 UTC, kunjgit commented
Thank you @Aksshay88 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-08 05:15 UTC, Aksshay88 commented
@kunjgit I have included the game You could review the PR and merge it .Thanks in advance

2024-06-08 15:49 UTC, Aksshay88 commented
@kunjgit I request you to review the PR once

2024-06-09 13:41 UTC, ishita-43 requested changes

2024-06-09 13:41 UTC, ishita-43 commented on assets/images/grab.png
Remove this if not needed or rename as your game name

2024-06-09 13:42 UTC, Aksshay88 commented
@ishita-43 will remove it

2024-06-09 13:46 UTC, Aksshay88 commented
@ishita-43 I have removed it .You could check the pr now

2024-06-09 14:03 UTC, ishita-43 approved these changes
Appreciate it ☻.
Ready to merge!!

2024-06-10 02:13 UTC, merged

2024-06-10 02:13 UTC, kunjgit commented
Thank you  @Aksshay88 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀