Fixes #4282
kunjgit/GameZone pull request #4285
Opened 2024-06-06 10:07 UTC by Sambit-Mondal

## PR Description 📜

Created a Intellect Quest Quiz Extension, which, takes uses the Open Trivia Database API to fetch questions, and after the user select one of the four options, the correct answer gets marked with green, and the rest gets marked with red.

Fixes #4282 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [z] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Screenshot 2024-06-05 170922](https://github.com/kunjgit/GameZone/assets/138088550/79592ab5-f2dd-412f-8f74-286dbb147108)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-06 10:07 UTC, kunjgit requested changes
Hello @Sambit-Mondal,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-06 10:15 UTC, kunjgit requested changes
Hello @Sambit-Mondal,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-06 10:18 UTC, kunjgit requested changes
Hello @Sambit-Mondal,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

2024-06-06 10:21 UTC, Sambit-Mondal commented
@kunjgit I've done the changes Sir. Kindly review

2024-06-09 13:43 UTC, ishita-43 requested changes

2024-06-09 13:43 UTC, ishita-43 commented on assets/images/Screenshot 2024-06-05 170922.png
Rename the file as per contribution guidelines for naming refer contribution.md

2024-06-09 14:57 UTC, Sambit-Mondal commented
@ishita-43 Hello, I've done the changes. Kindly check.
Thank you!

2024-06-09 15:31 UTC, ishita-43 approved these changes
Ready to merge!!

2024-06-10 02:13 UTC, merged

2024-06-10 02:13 UTC, kunjgit commented
Thank you  @Sambit-Mondal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀