soccer game added
kunjgit/GameZone pull request #4286
Opened 2024-06-06 10:25 UTC by bhumika-1127

@kunjgit I have added a soccer game wrt issue #4198.Kindly review the PR.

![Screenshot 2024-06-06 154128](https://github.com/kunjgit/GameZone/assets/137604220/7527df81-5d1d-4b4f-9e06-3a129aa823f9)

2024-06-06 10:25 UTC, kunjgit commented
Thank you @bhumika-1127 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-06 10:34 UTC, bhumika-1127 commented
\assign

2024-06-06 10:38 UTC, bhumika-1127 commented
/assign

2024-06-09 12:37 UTC, bhumika-1127 commented
@kunjgit Kindly review the pr.

2024-06-09 16:09 UTC, ishita-43 requested changes
Please make changes soon!!

2024-06-09 16:09 UTC, ishita-43 commented on assets/js/gamesData.json
> +  },"421":{"gameTitle": "Pen_Pointer_Fight",
remove this one if not intended!!

2024-06-09 16:09 UTC, ishita-43 commented on assets/js/gamesData.json
> +  },"421":{"gameTitle": "Pen_Pointer_Fight",
keep your project entry only

2024-06-09 16:09 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"423":{
after removing other your entry should be below 417 as 423

2024-06-09 16:09 UTC, ishita-43 commented on assets/js/index.js
if these changes are not compulsory dont make it

2024-06-09 16:13 UTC, bhumika-1127 commented on assets/js/index.js
@ishita-43 I don't get it I have added my game in it, if I remove other then those game might not be visible. Please elaborate what is to be done.

2024-06-09 17:22 UTC, ishita-43 commented on assets/js/index.js
there is no 418 in the entry the last entry we saw is 417 in the above file..

2024-06-09 17:22 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"423":{
did you added 421,422 also by yourself!!

2024-06-09 17:25 UTC, bhumika-1127 commented on assets/js/index.js
so next in sequence should be 418?

2024-06-09 17:35 UTC, ishita-43 commented on assets/js/index.js
it is not incresing like that 
if you look carefully the pattern is like this
406
415
407
416
408
417
409
418
and so on 
so if you are willing to add your game before 417 name it as 408
and if you yourself added morethan one game remove them from there or place them in similar pattern

2024-06-09 17:41 UTC, ishita-43 commented on assets/js/gamesData.json
> +  }
408 here one game

2024-06-09 17:41 UTC, ishita-43 commented on assets/js/gamesData.json
> + },"418":{
409 here second entry

2024-06-09 17:41 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"419":{"gameTitle": "Pen_Pointer_Fight",
should be as 418

2024-06-09 17:41 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"420":{
place this one in above space for 408 and remove from here also change label to 408

2024-06-09 17:41 UTC, bhumika-1127 commented on assets/js/index.js
@ishita-43 I have made the changes, kindly let me know it anything else is to be done.

2024-06-09 17:49 UTC, ishita-43 approved these changes
Good to go!!

2024-06-10 02:13 UTC, merged

2024-06-10 02:13 UTC, kunjgit commented
Thank you  @bhumika-1127 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀