planet colonizer added
kunjgit/GameZone pull request #4289
Opened 2024-06-06 11:11 UTC by Yashgabani845

## PR Description 📜

added planet colonizer 
added required 

1. html,css file
2. game logic in js
3. readme file for game
4.  game entry in readme and json
5.  added image in assets

Fixes #4287 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Screenshot (473)](https://github.com/kunjgit/GameZone/assets/127788321/601f397d-a984-4856-8460-620f483c4acd)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-06 11:11 UTC, kunjgit commented
Thank you @Yashgabani845 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-06 11:12 UTC, Yashgabani845 commented
@ishita-43  kindly review this PR
i have one evry steps of guideline and game as well 
thank you for opportunity

2024-06-09 18:29 UTC, ishita-43 requested changes
Hoping youwill make desired changes soon!!

2024-06-09 18:29 UTC, ishita-43 commented on assets/js/gamesData.json
> +  },"499":{
remove this from here!!

2024-06-09 18:29 UTC, ishita-43 commented on assets/js/gamesData.json
>    "thumbnailUrl": "Virtual_Pet_Game.png"
and place your game after this entry with no 82

2024-06-09 18:29 UTC, ishita-43 commented on assets/js/gamesData.json
> +},"511":{
remove this all

2024-06-13 18:12 UTC, closed without merging

2024-06-13 18:13 UTC, kunjgit commented
Thank you  @Yashgabani845 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀