Added new game Eco Warrior
kunjgit/GameZone pull request #4299
Opened 2024-06-06 14:59 UTC by Antiquely3059

## PR Description 📜
**Eco Warrior** is an educational and engaging game designed to raise awareness about environmental conservation. Players take on the role of an eco-warrior whose mission is to clean up litter, plant trees, and restore ecosystems. The game is designed to be both fun and educational, teaching players the importance of keeping the environment clean and green.

Fixes #4296 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Eco_Warrior](https://github.com/kunjgit/GameZone/assets/112797055/ab514ce7-8716-471f-b188-9419608b7f5b)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-09 18:44 UTC, ishita-43 requested changes
Hoping you will make desired changes soon!

2024-06-09 18:44 UTC, ishita-43 commented on README.md
> +| [Eco Warrior](https://github.com/Antiquely3059/GameZone/tree/main/Games/Eco%20Warrior)                                 | [Tilting Maze](https://github.com/kunjgit/GameZone/tree/main/Games/Tilting_M
change the link text as other specify in the pattern only placing your game name in the end!!

2024-06-10 12:56 UTC, Antiquely3059 commented
Updated the link text as you requested.

2024-06-19 04:39 UTC, Antiquely3059 commented
Please review it

2024-06-19 13:45 UTC, ishita-43 requested changes

2024-06-21 05:54 UTC, Antiquely3059 commented
I have updated the changes as you requested.
Please review it.

2024-06-21 17:03 UTC, ishita-43 requested changes

2024-06-21 17:03 UTC, ishita-43 commented on README.md
> +=======
remove this line!

2024-06-27 11:48 UTC, Antiquely3059 commented
I have updated the changes as you requested.
Please review it.

2024-07-04 08:32 UTC, ishita-43 approved these changes
Good to go!!

2024-07-04 08:34 UTC, ishita-43 commented
also Resolve merge conflicts

2024-07-04 15:53 UTC, Antiquely3059 commented
Resolved it

2024-07-06 17:25 UTC, ishita-43 commented on README.md
make sure  you added your game entry in this file and also that merge conflicts are resolved

2024-07-27 13:28 UTC, closed without merging

2024-07-27 13:29 UTC, kunjgit commented
Thank you  @Antiquely3059 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀