[new game]: Guess_the_friends_name
kunjgit/GameZone pull request #4304
Opened 2024-06-06 20:02 UTC by TiwariRahul16

## PR Description 📜
I have added new game : Guess the friends name.

Gameplay Overview: In “Guess the Friend's Name” players embark on a journey of memory and luck. player enters the names of four close friends into the game. The game then generates a random name from the list, and the player must use their intuition and knowledge about their friends to guess which name has been chosen.

Fixes #3931

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Guess the friends name](https://github.com/kunjgit/GameZone/assets/168175850/d3aaa3b9-44f6-4494-af01-6a15e52d1038)

![guess the friend name](https://github.com/kunjgit/GameZone/assets/168175850/6140bb0a-8de4-4557-ad17-8da829283015)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-06 20:02 UTC, kunjgit commented
Thank you @TiwariRahul16 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-07 18:47 UTC, TiwariRahul16 commented
/assign

2024-06-11 12:48 UTC, ishita-43 requested changes

2024-06-11 19:24 UTC, TiwariRahul16 commented
Hii @ishita-43 
Please Check 
I have Resolved conflict

2024-06-13 08:12 UTC, ishita-43 requested changes
pLEASE recheck entries made by you check if any duplicate is remaining

2024-06-14 18:52 UTC, TiwariRahul16 commented
> pLEASE recheck entries made by you check if any duplicate is remaining

no

2024-06-16 05:01 UTC, ishita-43 requested changes

2024-06-16 05:01 UTC, ishita-43 commented on README.md
Add your game entry in this file

2024-06-16 05:48 UTC, TiwariRahul16 commented on README.md
added

2024-06-16 06:10 UTC, ishita-43 requested changes
pLease make the desired changes

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +|[Turn_on_the_light](https://github.com/kunjgit/GameZone/tree/main/Games/Turn_on_the_light)   |
REMOVE THE DUPLICATE ENTRY

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +|[Chess_Game_computer](https://github.com/kunjgit/GameZone/tree/main/Games/Chess_Game_computer)   |
REMOVE THE DUPLICATE ENTRY

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +|[AquaSort_Game](https://github.com/kunjgit/GameZone/tree/main/Games/AquaSort_Game)   |
REMOVE THE DUPLICAT ENTRY

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +| [Brick Buster Game](https://github.com/kunjgit/GameZone/tree/main/Games/Brick Buster) |
REOVE THE DUPLICATE ENTRY

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +| [Dsa_quiz_game](https://github.com/kunjgit/GameZone/tree/main/Games/Dsa_quiz_game) |
REMOVE THE DUPLICATE ENTRY

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +| [Gravity_Simulation_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Gravity_Simulation_Game) |
REMOVE THE DUPLICATE CHANGES

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> +| [Brick Buster Game](https://github.com/kunjgit/GameZone/tree/main/Games/Brick Buster) |
REMOVE THE DUPLICATE CHANGES

2024-06-16 06:10 UTC, ishita-43 commented on README.md
> -| [Taash_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Taash_Game)|
ADD THIS ENTRY IN YOUR CHANGES

2024-06-16 13:43 UTC, TiwariRahul16 commented
done

2024-06-20 04:53 UTC, ishita-43 requested changes

2024-06-20 04:53 UTC, ishita-43 commented on README.md
> -|[Turn_on_the_light](https://github.com/kunjgit/GameZone/tree/main/Games/Turn_on_the_light)   |
add this entry in your file

2024-07-04 18:44 UTC, TiwariRahul16 commented
Hii @ishita-43 
can you please review and merge it

2024-07-07 10:02 UTC, ishita-43 commented
Resolve merge conflicts

2024-07-07 18:53 UTC, ishita-43 approved these changes
Good to go!!

2024-07-07 18:56 UTC, ishita-43 commented
You need to resolve arising merge conflicts i cant comprehend all changes myself quickly. iF IT seems tedious sync readme with latest changes then make your entry

2024-07-07 19:22 UTC, closed without merging

2024-07-07 19:22 UTC, kunjgit commented
Thank you  @TiwariRahul16 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀