[New game]: Bingo
kunjgit/GameZone pull request #4319
Opened 2024-06-07 13:21 UTC by Anjaliavv51

#4313

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4313

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![image](https://github.com/kunjgit/GameZone/assets/154777864/d10ba9c4-6782-4b6c-bd04-c9eca59d932a)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-07 13:21 UTC, kunjgit commented
Thank you @Anjaliavv51 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-07 13:21 UTC, Anjaliavv51 commented
/assign

2024-06-07 13:22 UTC, kunjgit requested changes
Hello @Anjaliavv51,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-07 13:22 UTC, Anjaliavv51 commented
@ishita-43 @kunjgit please review the Game

2024-06-07 13:27 UTC, kunjgit requested changes
Hello @Anjaliavv51,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-07 13:28 UTC, Anjaliavv51 commented
@ishita-43 @kunjgit please review the Game

2024-06-07 13:31 UTC, Anjaliavv51 commented
@ishita-43 @kunjgit please review the Game

2024-06-07 13:31 UTC, Anjaliavv51 commented
@ishita-43 @kunjgit please review the Game

2024-06-10 17:33 UTC, Anjaliavv51 commented
@kunjgit @ishita-43 please review the Game

2024-06-11 14:08 UTC, ishita-43 requested changes

2024-06-11 14:08 UTC, ishita-43 commented on assets/images/image.png
rename this image name as your game name read contribution .md for naming convention
I hope you will make changes soon!!

2024-06-11 14:08 UTC, ishita-43 commented on README.md
> +
add your game name here and see above entries for reference you need to follow the same format!!

2024-06-11 14:12 UTC, Anjaliavv51 commented
@ishita-43 review the changes

2024-06-11 14:12 UTC, Anjaliavv51 commented
![Screenshot_20240611_194238_GitHub.jpg](https://github.com/kunjgit/GameZone/assets/154777864/74a570b4-7bd6-4447-9b3b-6f43a94fa40a)

2024-06-11 14:15 UTC, ishita-43 commented on assets/images/image.png
rename as the name of your game folder

2024-06-11 15:00 UTC, closed without merging

2024-06-11 15:00 UTC, kunjgit commented
Thank you  @Anjaliavv51 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀