adding a rock paper scissor game
kunjgit/GameZone pull request #4323
Opened 2024-06-07 15:05 UTC by Vaishnavi1047

## PR Description 📜
Adding Stone Paper Scissor
Fixes #3905 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Screenshot 2024-06-07 202427](https://github.com/kunjgit/GameZone/assets/149894552/47b01758-cc62-499e-a88f-ac8381be7b28)

--- 
<br>
@kunjgit pls look into this

## Thank you soo much for contributing to our repository 💗

2024-06-07 15:05 UTC, kunjgit commented
Thank you @Vaishnavi1047 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-07 15:06 UTC, kunjgit requested changes
Hello @Vaishnavi1047,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-07 15:07 UTC, Vaishnavi1047 commented
ok sir

2024-06-07 15:12 UTC, kunjgit requested changes
Hello @Vaishnavi1047,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-07 15:20 UTC, Vaishnavi1047 commented
Update the readme like by adding what? It already have the info na?

2024-06-07 16:10 UTC, Vaishnavi1047 commented
and pls add the gssoc label in this issue

2024-06-11 14:18 UTC, ishita-43 requested changes

2024-06-11 14:18 UTC, ishita-43 commented on assets/images/rock-2004.png
rename image as name same as name of your game

2024-07-30 07:38 UTC, ishita-43 approved these changes
Good to merge

2024-07-30 16:05 UTC, kunjgit approved these changes

2024-07-30 16:05 UTC, merged

2024-07-30 16:05 UTC, kunjgit commented
Thank you  @Vaishnavi1047 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀