New Game: Catch_The_Falling_Objects
kunjgit/GameZone pull request #4336
Opened 2024-06-08 08:36 UTC by katarianikita2003

New Game: Catch_The_Falling_Objects

Game logic and basic description :
Objects will be falling from the top and we have to collect that at the bottom

Fixes  #4311 

Point down the features
-Score will be displayed.
-5 lives will be provided to the player.
-If player will not catch the objects, then player will loose 1 life
<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

![Catch The Falling Objects 1](https://github.com/kunjgit/GameZone/assets/158465309/82655cdb-4930-40d1-9ba2-beb37fe71775)

![Catch The Falling Objects 2](https://github.com/kunjgit/GameZone/assets/158465309/b9c02ffe-776f-4ff6-a1fa-775410593e47)

https://github.com/kunjgit/GameZone/assets/158465309/6e752df8-c658-45ff-bbe4-56024da6ae2f

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-08 08:37 UTC, katarianikita2003 commented
Heyy @kunjgit , please review it.

2024-06-10 18:08 UTC, katarianikita2003 commented
@kunjgit , please review it, either merge it or close it so that i can work on another issue

2024-06-11 14:27 UTC, ishita-43 requested changes

2024-06-11 14:27 UTC, ishita-43 commented on README.md
> +| [Knife_hit](https://github.com/kunjgit/GameZone/tree/main/Games/Knife_hit)       |
remove this if not needed

2024-06-11 17:46 UTC, katarianikita2003 commented on README.md
> +| [Knife_hit](https://github.com/kunjgit/GameZone/tree/main/Games/Knife_hit)       |
Only 237 Knife_hit?

2024-06-12 08:01 UTC, ishita-43 requested changes

2024-06-12 08:01 UTC, ishita-43 commented on assets/images/8_Puzzle.png
remove this if not needed

2024-06-12 08:01 UTC, ishita-43 commented on assets/images/Screenshot 2024-06-05 220940.png
delete if not needed

2024-06-16 03:54 UTC, ishita-43 requested changes
You need to add your game entry in main Readme.md file of the GameZone Repository.
Refer other entries for the format.

2024-06-20 11:28 UTC, ishita-43 approved these changes
Approved!!

2024-06-20 14:07 UTC, merged