Added Block_Ninja Game to the Repository
kunjgit/GameZone pull request #4337
Opened 2024-06-08 08:54 UTC by SumitKumar-17

## PR Description 📜

This PR adds the new game "Block Ninja" to the repository. Block Ninja is an engaging and addictive game where players must slash through blocks that appear on the screen while avoiding dangerous obstacles. The game tests the players' reflexes and precision as they aim to score the highest points. 

Fixes #3090

<hr>

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have followed proper naming conventions shown in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in `assets/images`
- [x] I have added entries for my game in the main README.md
- [x] I have added README.md in my folder 
- [ ] I have added a working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots (Optional) 📸
![Block_Ninja](https://github.com/kunjgit/GameZone/assets/118801141/e66b529c-4bf3-47ec-89b2-f00ae8e7abd0)

---

<br>

## Thank you so much for contributing to our repository 💗

2024-06-08 08:54 UTC, kunjgit commented
Thank you @SumitKumar-17 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-11 16:04 UTC, ishita-43 requested changes

2024-06-11 17:27 UTC, ishita-43 approved these changes
Good to go!!

2024-06-12 01:26 UTC, merged

2024-06-12 01:26 UTC, kunjgit commented
Thank you  @SumitKumar-17 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀