Added Alphabet and Vowels Game
kunjgit/GameZone pull request #4345
Opened 2024-06-08 10:39 UTC by manishh12

## PR Description 📜

The Alphabet and Vowel Game is an interactive web-based game designed to help players identify vowels and consonants. This game is ideal for educational purposes, providing a fun way to enhance letter recognition and differentiate between vowels and consonants. It offers a seamless and enjoyable experience for players of all ages.
Fixes #4331 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![image](https://github.com/kunjgit/GameZone/assets/97523900/03b0a814-d6f5-4aea-8ca9-7995947677e0)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-08 10:39 UTC, kunjgit commented
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-11 16:12 UTC, ishita-43 reviewed
Try to resolve merge conflicts

2024-06-11 16:12 UTC, ishita-43 commented on README.md
place your game 10 entries above in this position it is giving merge conflicts

2024-06-11 16:19 UTC, manishh12 commented
@ishita-43 Done ,kindly review it.

2024-06-11 16:25 UTC, ishita-43 requested changes

2024-06-11 16:25 UTC, ishita-43 commented on README.md
> +| [Brick Buster Game](https://github.com/kunjgit/GameZone/tree/main/Games/Brick Buster) |
remove duplicate entries

2024-06-11 16:25 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)
remove duplicate entry

2024-06-11 16:25 UTC, ishita-43 commented on README.md
> +|[Penguins Can't Fly](https://github.com/Will2Jacks/GameZoneForked/tree/Task/Games/Penguins_Can't_Fly)|
remove duplicate entry

2024-06-11 16:25 UTC, ishita-43 commented on README.md
> +| [Taash_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Taash_Game)|
remove duplicate entry

2024-06-11 16:31 UTC, manishh12 commented
@ishita-43 Kindly review it again sorry for the inconvenience.

2024-06-11 16:46 UTC, ishita-43 commented on README.md
> -| [Taash_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Taash_Game)|
add this one

2024-06-11 17:05 UTC, manishh12 commented
@ishita-43 Done.

2024-06-12 01:26 UTC, merged

2024-06-12 01:26 UTC, kunjgit commented
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀