Solved issue #4187- Tower Defence Game
kunjgit/GameZone pull request #4351
Opened 2024-06-08 13:29 UTC by Aditi22Bansal

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

In this game, players place defensive towers along a path to stop waves of enemies from reaching the end. Each tower has different abilities and ranges, and players can upgrade towers to improve their effectiveness.

Fixes # <your_issue_number>
Fixes #4187 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Screenshot 2024-06-04 004952](https://github.com/kunjgit/GameZone/assets/142652964/8e45c1a6-3309-4801-8c87-b6f0a8cb4291)
![Screenshot 2024-06-04 005003](https://github.com/kunjgit/GameZone/assets/142652964/0852eae4-2d1a-4818-b5ef-680a54f2461d)
![Tower_Game](https://github.com/kunjgit/GameZone/assets/142652964/a564fd5a-8fb5-4a46-b066-5903d3613d20)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-08 13:29 UTC, kunjgit commented
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-08 13:30 UTC, kunjgit requested changes
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-08 13:31 UTC, Aditi22Bansal commented
@ishita-43 
Kindly review this and approve
I have done it according to the changes you said in the previous PR
If any changes are still left to be done
Kindly tell
Thanks

2024-06-09 08:45 UTC, Aditi22Bansal commented
@ishita-43 
Kindly review the PR

2024-06-10 17:42 UTC, Aditi22Bansal commented
@ishita-43 
@kunjgit 
Kindly review the PR

2024-06-11 16:20 UTC, ishita-43 requested changes

2024-06-11 16:20 UTC, ishita-43 commented on README.md
> +| [Brick Buster Game](https://github.com/kunjgit/GameZone/tree/main/Games/Brick Buster) |
delete the duplicate copies before below brick buster game

2024-06-11 16:25 UTC, Aditi22Bansal commented
![image](https://github.com/kunjgit/GameZone/assets/142652964/d97afb07-413b-485d-850c-1b4dedf77fd6)
@ishita-43 
Done kindly review

2024-06-11 16:28 UTC, ishita-43 requested changes

2024-06-11 16:28 UTC, ishita-43 commented on README.md
> +| [Modulo_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Modulo_Game) |
remove this if not in  the repository

2024-06-11 16:28 UTC, ishita-43 commented on README.md
>  |[Tower Defence Game](https://github.com/Will2Jacks/GameZoneForked/tree/Task/Games/Tower_Defence_Game)|
add penguin and frenzy in the end and make sure to place the penguin in the below

2024-06-11 16:31 UTC, Aditi22Bansal commented
![image](https://github.com/kunjgit/GameZone/assets/142652964/6e1e3a0e-6232-4d03-9a03-c273e8231459)
@ishita-43 
Kindly check now

2024-06-11 16:35 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy) |
replace this one with modulo game

2024-06-11 16:43 UTC, Aditi22Bansal commented
![image](https://github.com/kunjgit/GameZone/assets/142652964/7cfc20b2-c751-478f-807c-e05d60256fdc)
@ishita-43 
Now check

2024-06-11 16:44 UTC, ishita-43 approved these changes
Good to go!!

2024-06-11 16:49 UTC, Aditi22Bansal commented
Thankyou so much @ishita-43 
Kindly merge

2024-06-11 16:54 UTC, ishita-43 commented
Merge will be done by Admin within 2-3 days. Till then you can explore other projects also and start working on issues.

2024-06-11 16:56 UTC, Aditi22Bansal commented
Okay thanks

2024-06-12 01:28 UTC, kunjgit commented
@Aditi22Bansal resolve merge conflicts

2024-06-12 07:57 UTC, ishita-43 commented
@kunjgit resolved!!

2024-06-12 08:59 UTC, Aditi22Bansal commented
Yes @kunjgit 
The conflicts are already resolved

2024-06-12 16:29 UTC, Aditi22Bansal commented
@ishita-43 
@kunjgit 
Kindly review and merge
I want to work on the other assigned issue
I have already worked just have to make the PR
It has been many days assigned to me that issue

2024-06-13 05:08 UTC, kunjgit commented
@Aditi22Bansal resolve merge conflicts !

2024-06-13 06:56 UTC, Aditi22Bansal commented
@kunjgit 
Kindly review 
Done the required changes

2024-06-13 14:41 UTC, Aditi22Bansal commented
@kunjgit
Kindly review
Done the required changes
I want to work on the other issue

2024-06-13 16:17 UTC, ishita-43 commented
it will soon be merged by the admin!

2024-06-14 05:17 UTC, kunjgit commented
> @Aditi22Bansal resolve merge conflicts !
> 

@Aditi22Bansal it's still there

2024-06-14 05:49 UTC, Aditi22Bansal commented
@kunjgit 
Due to late in merging 
Conflicts are arising again and again 
I have resolved the conflicts again
But kindly tell how to make it a permanent change

2024-06-15 02:40 UTC, merged

2024-06-15 02:40 UTC, kunjgit commented
Thank you  @Aditi22Bansal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀