Bubble'z popper
kunjgit/GameZone pull request #4371
Opened 2024-06-09 06:29 UTC by Chandu6702

## PR Description 📜

I added a simple bubble-popping game using HTML, CSS, and Javascript.
By moving the cursor onto the bubbles they blast. If you miss the 10 chances the game will end.

Fixes #4212 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Screenshot 2024-06-04 133640](https://github.com/kunjgit/GameZone/assets/125206920/a2e4e8b8-d05f-418e-9635-a1666731c93d)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-09 06:29 UTC, kunjgit commented
Thank you @Chandu6702 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-09 06:31 UTC, Chandu6702 commented
@kunjgit  please review and merge this PR

2024-06-10 12:51 UTC, Chandu6702 commented
@kunjgit please review and merge this PR

2024-06-11 05:57 UTC, Chandu6702 commented
@kunjgit please review and merge this PR

2024-06-11 11:51 UTC, Chandu6702 commented
@kunjgit please review and merge this PR

2024-06-11 11:52 UTC, Chandu6702 commented
@kunjgit please review and merge this PR

2024-06-12 06:34 UTC, Chandu6702 commented
@kunjgit please review and merge this PR

2024-06-12 06:38 UTC, Chandu6702 commented
@ishita-43 please review this PR

2024-06-12 16:41 UTC, Chandu6702 commented
@kunjgit please review and merge this pr

2024-06-12 16:45 UTC, Chandu6702 commented
@ishita-43 please review this PR

2024-06-13 06:14 UTC, Chandu6702 commented
@ishita-43 and @kunjgit please review this PR
It's been 3 days since I created this PR,
Other PRs which are created later have been merged
I don't know what's the problem can you please review this PR and let me know if I need to change anything.

2024-06-13 07:43 UTC, ishita-43 requested changes

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)
remove duplicate entry

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)
remove

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)          |
remove

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy)   |
remove

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +| [Gravity_Simulation_Game](https://github.com/kunjgit/GameZone/tree/main/Games/Gravity_Simulation_Game)   |
remove

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +|[Dsa_quiz_game](https://github.com/kunjgit/GameZone/tree/main/Games/Dsa_quiz_game)   |
remove

2024-06-13 07:43 UTC, ishita-43 commented on README.md
> +|[Penguins Can't Fly](https://github.com/Will2Jacks/GameZoneForked/tree/Task/Games/Penguins_Can't_Fly)|
remove

2024-06-13 08:31 UTC, Chandu6702 commented
@ishita-43 I have resolved the issues and updated the README.md file,please review this PR

2024-06-13 09:15 UTC, ishita-43 approved these changes
Good to go!!

2024-06-14 05:18 UTC, kunjgit commented
@Chandu6702 resolve merge conflicts

2024-06-14 05:26 UTC, Chandu6702 commented
@kunjgit I resolved the conflicts please review and merge this PR

2024-06-15 02:41 UTC, merged

2024-06-15 02:41 UTC, kunjgit commented
Thank you  @Chandu6702 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀