Noughts And Crosses
kunjgit/GameZone pull request #4376
Opened 2024-06-09 09:12 UTC by meetarora10

## PR Description 📜

Noughts and crosses is a game between two players, O and X, who alternate in marking the spaces in a 3×3 board. A player wins by getting three of their own marks in a horizontal, vertical or diagonal row. I have used technologies such as HTML,CSS and JavaScript.
Fixes #4375

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Screenshot (467)](https://github.com/kunjgit/GameZone/assets/143121854/c80d78c7-fb6d-46d3-aff4-ad50828dead0)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-09 09:13 UTC, kunjgit commented
Thank you @meetarora10 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-09 09:14 UTC, kunjgit requested changes
Hello @meetarora10,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-09 09:14 UTC, kunjgit requested changes
Hello @meetarora10,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

2024-06-09 09:15 UTC, kunjgit requested changes
Hello @meetarora10,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-09 09:15 UTC, kunjgit requested changes
Hello @meetarora10,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

2024-06-09 09:22 UTC, meetarora10 commented
@kunjgit I have made the changes.

2024-06-11 14:31 UTC, meetarora10 commented
@kunjgit I have resolved the merge conflicts please review once.

2024-06-11 16:59 UTC, ishita-43 requested changes

2024-06-11 16:59 UTC, ishita-43 commented on README.md
add your game entry around line number 325 refer other entries for format

2024-06-11 18:53 UTC, meetarora10 commented on README.md
Done.

2024-06-13 15:48 UTC, ishita-43 approved these changes
Good to go!!

2024-06-15 02:41 UTC, merged

2024-06-15 02:41 UTC, kunjgit commented
Thank you  @meetarora10 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀