Jigsaw Game added
kunjgit/GameZone pull request #4396
Opened 2024-06-10 02:02 UTC by Vipullakum007

## PR Description 📜

i have added Jigsaw game

Fixes #4395 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![jigsaw_game_1](https://github.com/kunjgit/GameZone/assets/127659443/2d4f653d-c8b8-417d-aec4-1d626c9f0339)
![jigsaw_game_2](https://github.com/kunjgit/GameZone/assets/127659443/5af6a74a-0a2d-4ef3-bb7b-fb3136fb47d4)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-10 02:02 UTC, kunjgit commented
Thank you @Vipullakum007 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-10 02:10 UTC, Vipullakum007 commented
hey @kunjgit @ishita-43 , ihave resolved conflics also now you can merge it.

2024-06-11 15:24 UTC, Vipullakum007 commented
hey @ishita-43 , please review it so that i can create new PR.

2024-06-11 17:21 UTC, ishita-43 requested changes
Add your game in readme.md file of the gamezone refer other entries for format 
make separate pr for the different games and include only game in one pr  that will help you in gaining more points for those pr
if you want to keep this in one only then tell me.

2024-06-11 17:21 UTC, ishita-43 commented on Games/Periodic_Table_Game/README.md
if this game is not the part of the jigsaw game remove this if it is the part then include this in your game folder

2024-06-11 17:21 UTC, ishita-43 commented on Games/Toast_Notification/README.md
if this game is not the part of the jigsaw game remove this if it is the part then include this in your game folder

2024-06-11 17:21 UTC, ishita-43 commented on assets/js/gamesData.json
> +"407":{
respectively remove these game entry

2024-06-12 02:55 UTC, closed without merging

2024-06-12 02:55 UTC, kunjgit commented
Thank you  @Vipullakum007 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

2024-06-12 02:56 UTC, Vipullakum007 commented
hey @ishita-43 , all conflicts are changed and i have created new PR