Russian Roulette
kunjgit/GameZone pull request #4404
Opened 2024-06-10 09:29 UTC by Harshitmishra001

## PR Description 📜

A simple Russian Roulette Game Where you test your luck by shooting bullets by Clicking a Button.
The Gun has a 33% chance of shooting and if shot a shooting sound plays and you die and the death counter increases.

Fixes #4384 

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Screenshot 2024-06-10 145820](https://github.com/kunjgit/GameZone/assets/131855565/7145b9a3-dd11-4aee-85c3-7d7869bce080)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-10 09:29 UTC, kunjgit commented
Thank you @Harshitmishra001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-12 15:51 UTC, ishita-43 requested changes

2024-06-12 15:51 UTC, ishita-43 commented on Games/Russian_Roulette/style.css
rename as your game folder name refer contribution guidelines

2024-06-12 15:59 UTC, Harshitmishra001 commented on Games/Russian_Roulette/style.css
Hey I am not understanding how I am supposed to name the folder?
The first letter is capital and _ is also used for spaces 
Files are also named correctly
Then what is the issue?

2024-06-13 08:54 UTC, ishita-43 commented on Games/Russian_Roulette/style.css
sorry i was referring your images in asset folder

2024-06-14 15:58 UTC, closed without merging

2024-06-14 15:59 UTC, kunjgit commented
Thank you  @Harshitmishra001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀