Added Word shuffle game
kunjgit/GameZone pull request #4407
Opened 2024-06-10 10:55 UTC by thevijayshankersharma

## PR Description 📜

Fixes #4406 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![image](https://github.com/kunjgit/GameZone/assets/109781385/abcc6c17-ebf2-4f61-8f21-9bfffbed0231)

<br>

## Thank you soo much for contributing to our repository 💗

2024-06-10 10:55 UTC, kunjgit commented
Thank you @thevijayshankersharma ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-12 15:56 UTC, ishita-43 requested changes

2024-06-12 15:56 UTC, ishita-43 commented on README.md
> +|[Dsa_quiz_game](https://github.com/kunjgit/GameZone/tree/main/Games/Dsa_quiz_game)   |
change with rapid click frenzy one

2024-06-12 16:26 UTC, thevijayshankersharma commented
@ishita-43 Is it okay now ??

2024-06-13 09:05 UTC, ishita-43 requested changes
Ensure no other duplicate entries are made by you

2024-06-13 09:05 UTC, ishita-43 commented on README.md
> +| [Brick Buster Game](https://github.com/kunjgit/GameZone/tree/main/Games/Brick Buster) |
remove this

2024-06-13 09:05 UTC, ishita-43 commented on README.md
> +| [Rapid_click_frenzy](https://github.com/kunjgit/GameZone/tree/main/Games/Rapid_click_frenzy) |
remove this

2024-06-13 09:05 UTC, ishita-43 commented on README.md
> +|[Penguins Can't Fly](https://github.com/Will2Jacks/GameZoneForked/tree/Task/Games/Penguins_Can't_Fly)|
remove this

2024-06-13 09:05 UTC, ishita-43 commented on README.md
> +| [Intellect Quest](https://github.com/Will2Jacks/GameZoneForked/tree/Task/Games/Intellect_Quest)|
remove this duplicate entry

2024-06-13 11:35 UTC, thevijayshankersharma commented
@ishita-43 @kunjgit All things is correct now. You can merge it.

2024-06-13 16:12 UTC, ishita-43 approved these changes
Good to go!

2024-06-15 02:41 UTC, merged

2024-06-15 02:41 UTC, kunjgit commented
Thank you  @thevijayshankersharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀