added new game Whack a mole
kunjgit/GameZone pull request #4477
Opened 2024-06-12 17:37 UTC by 1911aditi

## PR Description 📜

i have added a new game whack a mole.
pls assign me under GSSOC'24.
Fixes #4475 

<hr>
 
##4475

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![whack a mole](https://github.com/kunjgit/GameZone/assets/146438609/63086d4d-7e5b-454e-9140-6cc29263f1db)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-12 17:38 UTC, kunjgit commented
Thank you @1911aditi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-13 16:11 UTC, 1911aditi commented
I have resolved the issue
Can u check now?

2024-06-15 05:44 UTC, 1911aditi commented
Can u check now?

2024-06-16 11:26 UTC, ishita-43 requested changes
Please make the desired changes!!

2024-06-16 11:26 UTC, ishita-43 commented on README.md
> +|[AquaSort_Game](https://github.com/kunjgit/GameZone/tree/main/Games/AquaSort_Game)   |
remove the duplicate entry

2024-06-16 11:26 UTC, ishita-43 commented on README.md
> +| [Snake](https://github.com/kunjgit/GameZone/tree/main/Games/snake)                               |
remove this entry

2024-06-16 11:26 UTC, ishita-43 commented on README.md
> +|[AquaSort_Game](https://github.com/kunjgit/GameZone/tree/main/Games/AquaSort_Game) |
remove this entry

2024-06-16 11:26 UTC, ishita-43 commented on README.md
> +| [Snake](https://github.com/kunjgit/GameZone/tree/main/Games/snake)                |
remove this entry

2024-06-19 19:00 UTC, 1911aditi commented
check now

2024-06-20 11:58 UTC, ishita-43 approved these changes
Good to go!!

2024-06-20 14:08 UTC, kunjgit commented
@1911aditi resolve merge conflicts

2024-06-21 06:56 UTC, 1911aditi commented
check now

2024-06-21 08:56 UTC, merged

2024-06-21 08:56 UTC, kunjgit commented
Thank you  @1911aditi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀