Airhockey game
kunjgit/GameZone pull request #4503
Opened 2024-06-13 17:16 UTC by suhanibansal-05

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # 4496

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-13 17:16 UTC, kunjgit commented
Thank you @suhanibansal-05 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-16 11:15 UTC, ishita-43 requested changes
Please add your game image in asset folder of the gamezone

2024-06-20 04:59 UTC, ishita-43 requested changes

2024-06-20 04:59 UTC, ishita-43 commented on README.md
> +| [Airhockey_game](https://github.com/kunjgit/GameZone/tree/main/Games/Airhockey_game)|
remove this if duplicate entry

2024-07-28 10:58 UTC, ishita-43 commented on README.md
> +| [Airhockey_game](https://github.com/kunjgit/GameZone/tree/main/Games/Airhockey_game)|
Resolve merge conflicts

2024-07-30 07:43 UTC, ishita-43 approved these changes

2024-07-30 16:07 UTC, merged

2024-07-30 16:08 UTC, kunjgit commented
Thank you  @suhanibansal-05 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀