Added Mario Matching Game
kunjgit/GameZone pull request #4567
Opened 2024-06-16 10:23 UTC by ananyag309

Issue #4559 
1) I have added mario matching game, also added a readme file for instructions 
2) I have added images in asset
3) Provided the path of game in main readme. 

@ishita-43 please have check. and do add gssoc and level label. Thank you

https://github.com/kunjgit/GameZone/assets/145869907/49f83adc-3a42-4a59-9a4b-24d21f91a119

2024-06-16 10:24 UTC, kunjgit commented
Thank you @ananyag309 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-16 10:24 UTC, ananyag309 commented
/assign

2024-06-20 04:45 UTC, ishita-43 requested changes

2024-06-20 04:45 UTC, ishita-43 commented on README.md
> +|[Mario Matching Game](https://github.com/ananyag309/GameZone_ggsoc/tree/main/Games/Mario%20Matching%20Game)|
add the game entry format as others entries end the entry with your game name

2024-06-21 05:26 UTC, ananyag309 commented
updated read.me @ishita-43 ma'am please check

2024-06-21 16:59 UTC, ishita-43 approved these changes
Good to go!!

2024-06-24 08:34 UTC, merged

2024-06-24 08:34 UTC, kunjgit commented
Thank you  @ananyag309 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀