Adding Solitaire game
kunjgit/GameZone pull request #4613
Opened 2024-06-18 17:58 UTC by nikki-05

Created a new game page for Solitaire with the simplest design. ->Implemented game logic for Solitaire, including shuffle, deal, and move functionalities. ->made the game easy and simple
->Tested the Solitaire game for various browsers

## PR Description 📜

Integrated Solitaire game into the existing game website.
Created a new game page for Solitaire with a simple design.
Implemented game logic for Solitaire, including shuffle, deal, and move functionalities.
Added card movements and interactions.
Instructions and rules for playing Solitaire are included on the game page.
Tested the Solitaire game for various browsers and screen sizes to ensure compatibility and responsiveness.
Fixed minor bugs related to card placement and game reset functionality.
will be fixing more issues related to the game
Fixes #4564 

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas..
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-18 17:58 UTC, kunjgit commented
Thank you @nikki-05 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-18 18:00 UTC, nikki-05 commented
> Thank you @nikki-05 ,for creating the PR and contributing to our GameZone 💗 Review team will review the PR and will reach out to you soon! 😇 Make sure that you have marked all the tasks that you are done with ✅. Thank you for your patience! 😀

hello sir, how do I tick mark ?

2024-06-26 14:28 UTC, nikki-05 commented
hii @kunjgit may I know any update regarding the PR

2024-07-01 06:30 UTC, ishita-43 requested changes
Do the following changes 
add your game image in asset folder of the gamezone follow naming convention while naming the image add your game entry to the main readme.md file of the gammezone follow format (refer other entries)
also in your pr description mark anychanges that applied to your pr example part of program

2024-07-04 06:53 UTC, ishita-43 requested changes
also add your game entry into the main readme.md file of the repo refer other entries for the format

2024-07-04 06:53 UTC, ishita-43 commented on assets/images/Screenshot 2024-07-02 185338.png
rename as per naming convention for images should be same as game folder name

2024-07-04 12:20 UTC, nikki-05 commented on assets/images/Screenshot 2024-07-02 185338.png
hii can you check please if it is done

2024-07-05 16:32 UTC, ishita-43 commented on assets/images/Screenshot 2024-07-02 185338.png
its still not done you need to update readme.md file of the GameZone repo

2024-07-07 15:33 UTC, closed without merging

2024-07-07 15:33 UTC, kunjgit commented
Thank you  @nikki-05 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀