adde Makeover Game
kunjgit/GameZone pull request #4615
Opened 2024-06-18 19:07 UTC by abckhush

## PR Description 📜

added Makeover_Game
Fixes # 4603

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Makeover_Game](https://github.com/kunjgit/GameZone/assets/127378920/92071480-1b1e-4313-9c80-63c6cb63d4da)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-18 19:07 UTC, kunjgit commented
Thank you @abckhush ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-22 17:33 UTC, abckhush commented
Hi @ishita-43. Kindly review this PR.

2024-07-01 06:33 UTC, ishita-43 requested changes
Please addd your game image in asset folder of the gamezone and follow naming convention while naming that image

2024-07-01 16:55 UTC, abckhush commented
Hi @ishita-43  I have added, kindly check.

2024-07-04 07:03 UTC, ishita-43 requested changes

2024-07-04 07:03 UTC, ishita-43 commented on assets/images/Screenshot 2024-06-19 001746.png
rename the image same as your game folder name follow contribution guidelines for naming convention

2024-07-04 18:31 UTC, abckhush commented on assets/images/Screenshot 2024-06-19 001746.png
I am sorry for the overlook, can you check now?

2024-07-07 18:30 UTC, ishita-43 approved these changes
Good to go!!

2024-07-08 06:09 UTC, merged

2024-07-08 06:09 UTC, kunjgit commented
Thank you  @abckhush , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀