added Bubble Shooter game
kunjgit/GameZone pull request #4643
Opened 2024-06-20 18:09 UTC by SiriAmarlapudi

## PR Description 📜

I have created a bubble shooter game using html,css and javascript
Fixes # 4622

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-06-20 18:09 UTC, kunjgit commented
Thank you @SiriAmarlapudi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-06-22 08:53 UTC, SiriAmarlapudi commented
@ishita-43 please review it.

2024-06-24 17:13 UTC, SiriAmarlapudi commented
Please review it!!

2024-07-01 06:50 UTC, ishita-43 requested changes
Please add your game entry into the main readme.md file of the repository and make sure to follow the format while adding your game for that refer other game entries

2024-07-04 08:50 UTC, ishita-43 approved these changes
Good to go!!

2024-07-04 08:52 UTC, ishita-43 commented
Please resolve merge conflicts arising in the Readme.md file after that it will get merged .

2024-07-08 14:18 UTC, SiriAmarlapudi commented
there are no merge conflicts...Can u merge this game

2024-07-09 07:26 UTC, ishita-43 commented
> there are no merge conflicts...Can u merge this game

Pr will soon be merged by the admin!!

2024-07-09 10:10 UTC, merged

2024-07-09 10:10 UTC, kunjgit commented
Thank you  @SiriAmarlapudi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀