adding a new game dodge teh blocks
kunjgit/GameZone pull request #4752
Opened 2024-07-06 14:47 UTC by 1911aditi

## PR Description 📜

In this game, the player controls a character that must avoid falling blocks. The goal is to survive as long as possible without being hit.

Fixes #4751

<hr>
 
##4751 ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Screenshot 2024-07-06 200816](https://github.com/kunjgit/GameZone/assets/146438609/a1bed5ee-24f5-44b0-ae0c-05d9dfdd83d0)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-06 14:47 UTC, kunjgit commented
Thank you @1911aditi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-08 10:59 UTC, ishita-43 requested changes
I HOpe you will make the desired changes soon

2024-07-08 10:59 UTC, ishita-43 commented on assets/images/Screenshot 2024-07-06 200816.png
Hi please rename the image as per contribution guidelines for naming conventions

2024-07-08 11:21 UTC, ishita-43 commented on assets/images/Screenshot 2024-07-06 200816.png
you need to change the name of this image also as dodge_the_blocks.png

2024-07-08 18:51 UTC, 1911aditi commented
can u check now?

2024-07-09 08:00 UTC, ishita-43 approved these changes
Good to go!!

2024-07-09 10:11 UTC, merged

2024-07-09 10:11 UTC, kunjgit commented
Thank you  @1911aditi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀