Fead/add snake gun water game
kunjgit/GameZone pull request #4840
Opened 2024-07-12 17:43 UTC by ANKeshri

## PR Description 📜

In this game winner will get 1 point. if both choose the same then both will get 1 points. in total of 10 rounds who gets the highest points will be considered as winner . Please see the video attached . Its ui is lookig good . 

Fixes #4820 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/b06116c3-2df1-42b6-87cb-3a8d3d5d6690

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-12 17:43 UTC, kunjgit commented
Thank you @ANKeshri ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-14 09:12 UTC, ANKeshri commented
@kunjgit please review and merge my pr

2024-07-16 15:10 UTC, ANKeshri commented
/assign

2024-07-17 15:51 UTC, ishita-43 requested changes
Please update your pr and make following changes

2024-07-17 15:51 UTC, ishita-43 commented on README.md
Please add your game entry into this file as other game and replace the ending with your game folder name

2024-07-17 15:51 UTC, ishita-43 commented on assets/images/image.png
Follow contribution.md for naming convention while naming the file name of the image of your game 
eg yourgame.png

2024-07-17 16:48 UTC, ANKeshri commented
> Please update your pr and make following changes

done the requested changes @ishita-43

2024-07-17 19:41 UTC, ishita-43 approved these changes
Good to go

2024-07-18 16:18 UTC, kunjgit approved these changes

2024-07-18 16:18 UTC, merged

2024-07-18 16:19 UTC, kunjgit commented
Thank you  @ANKeshri , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀