Cow Bull game
kunjgit/GameZone pull request #4848
Opened 2024-07-14 07:13 UTC by mukilan2815

## PR Description 📜

Fixes #4799 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![image](https://github.com/user-attachments/assets/1b236d92-8652-473a-8f63-c349a93f96f2)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-14 07:13 UTC, kunjgit commented
Thank you @mukilan2815 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-17 16:06 UTC, ishita-43 requested changes
Please make the needed changes in your PR

2024-07-17 16:06 UTC, ishita-43 commented on README.md
pLease sync your readme file with latest changes  and only add than your game entry in there

2024-07-29 13:47 UTC, ishita-43 commented
Please resolve merge conflicts

2024-07-29 14:13 UTC, closed without merging

2024-07-29 14:14 UTC, mukilan2815 commented
oops sorry i will PR again

2024-07-29 14:14 UTC, mukilan2815 commented
done

2024-07-29 14:27 UTC, mukilan2815 commented
@ishita-43  #5020 i have created there and i will close here. please merge