New Game: Matching_Pair_Game
kunjgit/GameZone pull request #4871
Opened 2024-07-16 18:19 UTC by priyashuu

## PR Description 📜

he Matching Pairs Game is a fun and engaging memory game developed using HTML, CSS, and JavaScript. The game challenges players to match pairs of cards with identical images within a limited time. It offers a simple yet addictive gameplay experience, enhanced with a sleek user interface .
Fixes # <4844>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
![Matching_Pair_Game](https://github.com/user-attachments/assets/2fd4c253-0671-4911-b358-aea06aaf9cc4)
## workingVideo
https://github.com/user-attachments/assets/761e65a1-6ef8-49ec-ac12-574ea1e15555

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-16 18:19 UTC, kunjgit commented
Thank you @priyashuu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-17 16:12 UTC, priyashuu commented
/assign

2024-07-17 16:24 UTC, ishita-43 requested changes
You need to check following changes in your PR

2024-07-17 16:24 UTC, ishita-43 commented on README.md
> -| [Simon_Says](https://github.com/kunjgit/GameZone/tree/main/Games/Simon_Says) |
these game entry are missing from your file simon says, idle  miner, five nights at freddys
make sure your file is in sync with latest changes

2024-07-17 16:24 UTC, ishita-43 commented on README.md
> +|[Matching_Pair](https://github.com/priyashuu/GameZone/tree/main/Games/Matching_pair)
change the your id name with kunjgit to make changes visible on the site as other entries do

2024-07-19 12:15 UTC, ishita-43 commented
Resolve merge conflicts

2024-07-21 04:39 UTC, priyashuu commented
okay Done ...

2024-07-21 09:22 UTC, ishita-43 approved these changes
Good to go!!

2024-07-21 15:06 UTC, priyashuu commented
Thank you ⭐🫡❤️

2024-07-22 02:36 UTC, merged

2024-07-22 02:36 UTC, kunjgit commented
Thank you  @priyashuu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀