Issue no. #4730
kunjgit/GameZone pull request #4934
Opened 2024-07-22 16:29 UTC by gopi-trip

## PR Description 📜
Completed the RPG Game
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-22 16:29 UTC, kunjgit commented
Thank you @gopi-trip ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-23 13:14 UTC, ishita-43 requested changes
Please make following changes 
add your game entry into main readme.md file of the repo 
add your game image in the asset folder of the gamezone

2024-07-23 14:47 UTC, gopi-trip commented
@ishita-43 I am not sure if I added the entry right. Please advice me if I did not.

2024-07-28 08:18 UTC, gopi-trip commented
@ishita-43 Please review and merge this

2024-07-28 08:19 UTC, ishita-43 commented on README.md
> +| [Dragon_Slayer](https://github.com/gopi-trip/GameZone/tree/main/Games/Dragon_Slayer) |
Change the name to kunjgit as other did instead of your repo name to make it work

2024-07-28 08:19 UTC, ishita-43 commented on README.md
> +=======
Remove this line

2024-07-28 08:24 UTC, gopi-trip commented
Done with the change

2024-07-28 08:38 UTC, ishita-43 commented
> @ishita-43, Done with the change

==== are showing various places that need to be removed also

2024-07-29 06:32 UTC, ishita-43 approved these changes

2024-07-29 06:33 UTC, ishita-43 commented
Also resolve arising merge conflicts

2024-07-29 10:28 UTC, merged

2024-07-29 10:29 UTC, kunjgit commented
Thank you  @gopi-trip , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀