Added New Game: Ping pong
kunjgit/GameZone pull request #5036
Opened 2024-07-30 14:38 UTC by AaryanManghnani

## PR Description 📜

A Class Ping Pong Game in which both players control their paddles and defend their side while trying to score on their opponent.
Fixes #5034

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
![image](https://github.com/AaryanManghnani/GameZone/blob/Ping_Pong/assets/images/Ping_Pong.png)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-30 14:39 UTC, kunjgit commented
Thank you @AaryanManghnani ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-07-31 06:04 UTC, ishita-43 requested changes
Please make following update

2024-07-31 06:04 UTC, ishita-43 commented on README.md
> +|[Ping_Pong](https://github.com/AaryanManghnani/GameZone/tree/Ping_Pong/Games/Ping_Pong)
Chane name of the repo to kunjgit instead of your repo name

2024-07-31 06:05 UTC, ishita-43 commented on README.md
> +|[Ping_Pong](https://github.com/AaryanManghnani/GameZone/tree/Ping_Pong/Games/Ping_Pong)
> refer other entries for the format

2024-07-31 13:51 UTC, ishita-43 approved these changes
Pr is ready to merge

2024-08-01 11:04 UTC, merged

2024-08-01 11:05 UTC, kunjgit commented
Thank you  @AaryanManghnani , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀