Adding a game smash monty mole, contributing under GSSOC'24
kunjgit/GameZone pull request #5053
Opened 2024-07-31 19:12 UTC by rugved0102

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in GameZone's README.md
- [ ] I have added README.md in my Game folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.
- [ ] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
![image](https://github.com/user-attachments/assets/2860818f-57ea-4e34-bb99-d3cbc875a34e)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2024-07-31 19:12 UTC, kunjgit commented
Thank you @rugved0102 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2024-08-01 14:48 UTC, ishita-43 commented
What is your issue number?

2024-08-01 14:49 UTC, ishita-43 requested changes
Add your game entry into readme. Md file of the gamezone repo 
Add your game image into the assets folder of the gamezone

2024-08-02 13:56 UTC, rugved0102 commented
Done with the requested changes. Any suggested modification ??
I am contributing under gssoc'24 so I request you to label it

2024-08-02 15:38 UTC, ishita-43 requested changes
Please make following changes

2024-08-02 15:38 UTC, ishita-43 commented on README.md
> +|[Smash-Monty-Mole]()|
Add your link also would be same as other only add your game folder name in the end

2024-08-02 17:59 UTC, rugved0102 commented
done !

2024-08-03 07:28 UTC, ishita-43 approved these changes
Approved

2024-08-04 07:32 UTC, merged

2024-08-04 07:32 UTC, kunjgit commented
Thank you  @rugved0102 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀