Added Love_Calci
kunjgit/GameZone pull request #728
Opened 2023-06-02 15:09 UTC by shivani-tripurari

## PR Description 📜

I added Love calculator game which predicts the love score and gives a unique message.
<your_issue_number>
#534
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-06-02 15:09 UTC, kunjgit commented
Thank you @shivani-tripurari ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

2023-06-02 15:13 UTC, shivani-tripurari commented
Thanks @kunjgit  do notify me soon if any changes are needed.

2023-06-03 06:54 UTC, kunjgit requested changes
add your game image in main repo assets/images

2023-06-07 11:59 UTC, kunjgit approved these changes

2023-06-07 11:59 UTC, merged