add ludo-game
kunjgit/GameZone pull request #86
Opened 2023-05-20 12:48 UTC by Gurnav224

## PR Description 📜
I add a ludo game

Fixes # 40

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

2023-05-23 04:32 UTC, kunjgit requested changes

2023-05-23 04:32 UTC, kunjgit commented on README.md
don't add number over here and make sure you mention * as number as we are adding games it will conflicts !! 
make the changes !!

2023-05-23 04:47 UTC, Gurnav224 commented on README.md
i can't understand where to remove the number can you please tell where to remove the number

2023-05-24 06:45 UTC, kunjgit commented
please mention the issue on which you were working and make a PR again !!

2023-05-24 06:45 UTC, closed without merging

2023-05-24 06:45 UTC, kunjgit commented
Thank you  @Gurnav224 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀